project:
  type: website

website:
  title: "Rhian Davies"
  navbar:
    logo: "img/letter-R.png"
    logo-alt: "A handwritten, blue, letter R"
    right:
      - text: "ğŸ‘‹ğŸ» About"
        file: index.qmd
      - text: "ğŸ‘©ğŸ»â€ğŸ« Talks"
        file: talks.qmd
      - text: "âœğŸ» Blog"
        file: posts.qmd
      - text: "ğŸŒ± Thoughts"
        href: https://statsrhian-garden.netlify.app/
      - text: "âœ¨ Now"
        file: now.qmd

format: html

execute: 
  freeze: auto